//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSharpParser.g4 by ANTLR 4.7.1

//Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CSharpParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
public interface ICSharpParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_unit([NotNull] CSharpParser.Compilation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.namespace_or_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_or_type_name([NotNull] CSharpParser.Namespace_or_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CSharpParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.base_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_type([NotNull] CSharpParser.Base_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.simple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type([NotNull] CSharpParser.Simple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_type([NotNull] CSharpParser.Numeric_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.integral_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegral_type([NotNull] CSharpParser.Integral_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.floating_point_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloating_point_type([NotNull] CSharpParser.Floating_point_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type([NotNull] CSharpParser.Class_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list([NotNull] CSharpParser.Type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] CSharpParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] CSharpParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CSharpParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_assignment_expression([NotNull] CSharpParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] CSharpParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] CSharpParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] CSharpParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.null_coalescing_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_coalescing_expression([NotNull] CSharpParser.Null_coalescing_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_or_expression([NotNull] CSharpParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_and_expression([NotNull] CSharpParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusive_or_expression([NotNull] CSharpParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusive_or_expression([NotNull] CSharpParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expression([NotNull] CSharpParser.And_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality_expression([NotNull] CSharpParser.Equality_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expression([NotNull] CSharpParser.Relational_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] CSharpParser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expression([NotNull] CSharpParser.Additive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expression([NotNull] CSharpParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] CSharpParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] CSharpParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] CSharpParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleNameExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleNameExpression([NotNull] CSharpParser.SimpleNameExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpressions([NotNull] CSharpParser.ParenthesisExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>memberAccessExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccessExpression([NotNull] CSharpParser.MemberAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalAccessExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralAccessExpression([NotNull] CSharpParser.LiteralAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>thisReferenceExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThisReferenceExpression([NotNull] CSharpParser.ThisReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>baseAccessExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseAccessExpression([NotNull] CSharpParser.BaseAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>objectCreationExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreationExpression([NotNull] CSharpParser.ObjectCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeofExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeofExpression([NotNull] CSharpParser.TypeofExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>checkedExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheckedExpression([NotNull] CSharpParser.CheckedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>uncheckedExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUncheckedExpression([NotNull] CSharpParser.UncheckedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>defaultValueExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultValueExpression([NotNull] CSharpParser.DefaultValueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>anonymousMethodExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymousMethodExpression([NotNull] CSharpParser.AnonymousMethodExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sizeofExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSizeofExpression([NotNull] CSharpParser.SizeofExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nameofExpression</c>
	/// labeled alternative in <see cref="CSharpParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameofExpression([NotNull] CSharpParser.NameofExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_access([NotNull] CSharpParser.Member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.bracket_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_expression([NotNull] CSharpParser.Bracket_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.indexer_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexer_argument([NotNull] CSharpParser.Indexer_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.predefined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type([NotNull] CSharpParser.Predefined_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] CSharpParser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.object_or_collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_or_collection_initializer([NotNull] CSharpParser.Object_or_collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_initializer([NotNull] CSharpParser.Object_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer_list([NotNull] CSharpParser.Member_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer([NotNull] CSharpParser.Member_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.initializer_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_value([NotNull] CSharpParser.Initializer_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollection_initializer([NotNull] CSharpParser.Collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_initializer([NotNull] CSharpParser.Element_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.anonymous_object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_object_initializer([NotNull] CSharpParser.Anonymous_object_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator_list([NotNull] CSharpParser.Member_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator([NotNull] CSharpParser.Member_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.unbound_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnbound_type_name([NotNull] CSharpParser.Unbound_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.generic_dimension_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_dimension_specifier([NotNull] CSharpParser.Generic_dimension_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.isType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsType([NotNull] CSharpParser.IsTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_expression([NotNull] CSharpParser.Lambda_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.anonymous_function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_signature([NotNull] CSharpParser.Anonymous_function_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.explicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter_list([NotNull] CSharpParser.Explicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.explicit_anonymous_function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_anonymous_function_parameter([NotNull] CSharpParser.Explicit_anonymous_function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.implicit_anonymous_function_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicit_anonymous_function_parameter_list([NotNull] CSharpParser.Implicit_anonymous_function_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.anonymous_function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_function_body([NotNull] CSharpParser.Anonymous_function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_expression([NotNull] CSharpParser.Query_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.from_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_clause([NotNull] CSharpParser.From_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.query_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_body([NotNull] CSharpParser.Query_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.query_body_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_body_clause([NotNull] CSharpParser.Query_body_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.let_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet_clause([NotNull] CSharpParser.Let_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_clause([NotNull] CSharpParser.Where_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.combined_join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCombined_join_clause([NotNull] CSharpParser.Combined_join_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.orderby_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderby_clause([NotNull] CSharpParser.Orderby_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.ordering"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdering([NotNull] CSharpParser.OrderingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.select_or_group_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_or_group_clause([NotNull] CSharpParser.Select_or_group_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.query_continuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_continuation([NotNull] CSharpParser.Query_continuationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>labeledStatement</c>
	/// labeled alternative in <see cref="CSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] CSharpParser.LabeledStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declarationStatement</c>
	/// labeled alternative in <see cref="CSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] CSharpParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>embeddedStatement</c>
	/// labeled alternative in <see cref="CSharpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbeddedStatement([NotNull] CSharpParser.EmbeddedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.labeled_Statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeled_Statement([NotNull] CSharpParser.Labeled_StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbedded_statement([NotNull] CSharpParser.Embedded_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>emptyStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] CSharpParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CSharpParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CSharpParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] CSharpParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] CSharpParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStatement([NotNull] CSharpParser.DoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] CSharpParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>foreachStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStatement([NotNull] CSharpParser.ForeachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] CSharpParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] CSharpParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>gotoStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStatement([NotNull] CSharpParser.GotoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] CSharpParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>throwStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] CSharpParser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tryStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryStatement([NotNull] CSharpParser.TryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>checkedStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCheckedStatement([NotNull] CSharpParser.CheckedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>uncheckedStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUncheckedStatement([NotNull] CSharpParser.UncheckedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lockStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLockStatement([NotNull] CSharpParser.LockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStatement([NotNull] CSharpParser.UsingStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>yieldStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldStatement([NotNull] CSharpParser.YieldStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unsafeStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsafeStatement([NotNull] CSharpParser.UnsafeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fixedStatement</c>
	/// labeled alternative in <see cref="CSharpParser.simple_embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedStatement([NotNull] CSharpParser.FixedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] CSharpParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declaration([NotNull] CSharpParser.Local_variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_variable_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_type([NotNull] CSharpParser.Local_variable_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_declarator([NotNull] CSharpParser.Local_variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_initializer([NotNull] CSharpParser.Local_variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_constant_declaration([NotNull] CSharpParser.Local_constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.if_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_body([NotNull] CSharpParser.If_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.switch_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_section([NotNull] CSharpParser.Switch_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.switch_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_label([NotNull] CSharpParser.Switch_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] CSharpParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.for_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_initializer([NotNull] CSharpParser.For_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.for_iterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_iterator([NotNull] CSharpParser.For_iteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.catch_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clauses([NotNull] CSharpParser.Catch_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.specific_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecific_catch_clause([NotNull] CSharpParser.Specific_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.general_catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_catch_clause([NotNull] CSharpParser.General_catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.exception_filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitException_filter([NotNull] CSharpParser.Exception_filterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.finally_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_clause([NotNull] CSharpParser.Finally_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.resource_acquisition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_acquisition([NotNull] CSharpParser.Resource_acquisitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.namespace_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_declaration([NotNull] CSharpParser.Namespace_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.qualified_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_identifier([NotNull] CSharpParser.Qualified_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.namespace_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_body([NotNull] CSharpParser.Namespace_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.extern_alias_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtern_alias_directives([NotNull] CSharpParser.Extern_alias_directivesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.extern_alias_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtern_alias_directive([NotNull] CSharpParser.Extern_alias_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.using_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsing_directives([NotNull] CSharpParser.Using_directivesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingAliasDirective</c>
	/// labeled alternative in <see cref="CSharpParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingAliasDirective([NotNull] CSharpParser.UsingAliasDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingNamespaceDirective</c>
	/// labeled alternative in <see cref="CSharpParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingNamespaceDirective([NotNull] CSharpParser.UsingNamespaceDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>usingStaticDirective</c>
	/// labeled alternative in <see cref="CSharpParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStaticDirective([NotNull] CSharpParser.UsingStaticDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.namespace_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declarations([NotNull] CSharpParser.Namespace_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.namespace_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_member_declaration([NotNull] CSharpParser.Namespace_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] CSharpParser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.qualified_alias_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_alias_member([NotNull] CSharpParser.Qualified_alias_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_list([NotNull] CSharpParser.Type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter([NotNull] CSharpParser.Type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_base([NotNull] CSharpParser.Class_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_type_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_type_list([NotNull] CSharpParser.Interface_type_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_parameter_constraints_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints_clauses([NotNull] CSharpParser.Type_parameter_constraints_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_parameter_constraints_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints_clause([NotNull] CSharpParser.Type_parameter_constraints_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.type_parameter_constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_constraints([NotNull] CSharpParser.Type_parameter_constraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.primary_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_constraint([NotNull] CSharpParser.Primary_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.secondary_constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_constraints([NotNull] CSharpParser.Secondary_constraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constructor_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_constraint([NotNull] CSharpParser.Constructor_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body([NotNull] CSharpParser.Class_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_member_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declarations([NotNull] CSharpParser.Class_member_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member_declaration([NotNull] CSharpParser.Class_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.all_member_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifiers([NotNull] CSharpParser.All_member_modifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.all_member_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_member_modifier([NotNull] CSharpParser.All_member_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.common_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_member_declaration([NotNull] CSharpParser.Common_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.typed_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTyped_member_declaration([NotNull] CSharpParser.Typed_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constant_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declarators([NotNull] CSharpParser.Constant_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constant_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declarator([NotNull] CSharpParser.Constant_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variable_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarators([NotNull] CSharpParser.Variable_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarator([NotNull] CSharpParser.Variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer([NotNull] CSharpParser.Variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] CSharpParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_name([NotNull] CSharpParser.Member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.method_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_body([NotNull] CSharpParser.Method_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] CSharpParser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameters([NotNull] CSharpParser.Fixed_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_parameter([NotNull] CSharpParser.Fixed_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.parameter_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_modifier([NotNull] CSharpParser.Parameter_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.parameter_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_array([NotNull] CSharpParser.Parameter_arrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.accessor_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor_declarations([NotNull] CSharpParser.Accessor_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.get_accessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGet_accessor_declaration([NotNull] CSharpParser.Get_accessor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.set_accessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_accessor_declaration([NotNull] CSharpParser.Set_accessor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.accessor_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor_modifier([NotNull] CSharpParser.Accessor_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.accessor_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor_body([NotNull] CSharpParser.Accessor_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.event_accessor_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvent_accessor_declarations([NotNull] CSharpParser.Event_accessor_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.add_accessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_accessor_declaration([NotNull] CSharpParser.Add_accessor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.remove_accessor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemove_accessor_declaration([NotNull] CSharpParser.Remove_accessor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.overloadable_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOverloadable_operator([NotNull] CSharpParser.Overloadable_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.conversion_operator_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversion_operator_declarator([NotNull] CSharpParser.Conversion_operator_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constructor_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_initializer([NotNull] CSharpParser.Constructor_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] CSharpParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.struct_interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_interfaces([NotNull] CSharpParser.Struct_interfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_body([NotNull] CSharpParser.Struct_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.struct_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member_declaration([NotNull] CSharpParser.Struct_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type([NotNull] CSharpParser.Array_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.rank_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank_specifier([NotNull] CSharpParser.Rank_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.array_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_initializer([NotNull] CSharpParser.Array_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variant_type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter_list([NotNull] CSharpParser.Variant_type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variant_type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_type_parameter([NotNull] CSharpParser.Variant_type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.variance_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariance_annotation([NotNull] CSharpParser.Variance_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_base([NotNull] CSharpParser.Interface_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_body([NotNull] CSharpParser.Interface_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_member_declaration([NotNull] CSharpParser.Interface_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_accessors"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_accessors([NotNull] CSharpParser.Interface_accessorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.enum_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_base([NotNull] CSharpParser.Enum_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.enum_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_body([NotNull] CSharpParser.Enum_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.enum_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_member_declaration([NotNull] CSharpParser.Enum_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.global_attribute_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_attribute_section([NotNull] CSharpParser.Global_attribute_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.global_attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_attribute_target([NotNull] CSharpParser.Global_attribute_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] CSharpParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attribute_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_section([NotNull] CSharpParser.Attribute_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_target([NotNull] CSharpParser.Attribute_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attribute_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_list([NotNull] CSharpParser.Attribute_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] CSharpParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.attribute_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_argument([NotNull] CSharpParser.Attribute_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.pointer_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer_type([NotNull] CSharpParser.Pointer_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_pointer_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_pointer_declarators([NotNull] CSharpParser.Fixed_pointer_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_pointer_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_pointer_declarator([NotNull] CSharpParser.Fixed_pointer_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_pointer_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_pointer_initializer([NotNull] CSharpParser.Fixed_pointer_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.fixed_size_buffer_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixed_size_buffer_declarator([NotNull] CSharpParser.Fixed_size_buffer_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.local_variable_initializer_unsafe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_initializer_unsafe([NotNull] CSharpParser.Local_variable_initializer_unsafeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.right_arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_arrow([NotNull] CSharpParser.Right_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.right_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift([NotNull] CSharpParser.Right_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.right_shift_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift_assignment([NotNull] CSharpParser.Right_shift_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CSharpParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] CSharpParser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] CSharpParser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interpolated_regular_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_regular_string([NotNull] CSharpParser.Interpolated_regular_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interpolated_verbatium_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_verbatium_string([NotNull] CSharpParser.Interpolated_verbatium_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interpolated_regular_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_regular_string_part([NotNull] CSharpParser.Interpolated_regular_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interpolated_verbatium_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_verbatium_string_part([NotNull] CSharpParser.Interpolated_verbatium_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interpolated_string_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_string_expression([NotNull] CSharpParser.Interpolated_string_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] CSharpParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_definition([NotNull] CSharpParser.Class_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.struct_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_definition([NotNull] CSharpParser.Struct_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.interface_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_definition([NotNull] CSharpParser.Interface_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.enum_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_definition([NotNull] CSharpParser.Enum_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.delegate_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegate_definition([NotNull] CSharpParser.Delegate_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.event_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvent_declaration([NotNull] CSharpParser.Event_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.field_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_declaration([NotNull] CSharpParser.Field_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty_declaration([NotNull] CSharpParser.Property_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declaration([NotNull] CSharpParser.Constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.indexer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexer_declaration([NotNull] CSharpParser.Indexer_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.destructor_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructor_definition([NotNull] CSharpParser.Destructor_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_declaration([NotNull] CSharpParser.Constructor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_declaration([NotNull] CSharpParser.Method_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.method_member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_member_name([NotNull] CSharpParser.Method_member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_declaration([NotNull] CSharpParser.Operator_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.arg_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg_declaration([NotNull] CSharpParser.Arg_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.method_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_invocation([NotNull] CSharpParser.Method_invocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.object_creation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_creation_expression([NotNull] CSharpParser.Object_creation_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CSharpParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] CSharpParser.IdentifierContext context);
}
